// Life Event Scenarios unlocked at XP milestones
export const LIFE_EVENT_SCENARIOS = [
  {
    id: "starter",
    title: "First Job & First Budget",
    emoji: "🏁",
    xpRequired: 0,
    difficulty: 1,
    tag: "Beginner",
    tagColor: "bg-primary/10 text-primary border-primary/20",
    description: "You just landed your first job. Navigate rent, groceries, and your first paycheck.",
    challenges: ["Write your first paycheck", "Set up a basic budget", "Open a checking account"],
  },
  {
    id: "car_purchase",
    title: "Buy vs. Lease a Car",
    emoji: "🚗",
    xpRequired: 100,
    difficulty: 2,
    tag: "Intermediate",
    tagColor: "bg-chart-5/10 text-chart-5 border-chart-5/20",
    description: "Your old car broke down. Compare loan payments, insurance costs, and total cost of ownership.",
    challenges: ["Calculate monthly loan payment", "Compare buy vs. lease", "Factor in insurance & gas"],
  },
  {
    id: "medical_debt",
    title: "Surprise Medical Bill",
    emoji: "🏥",
    xpRequired: 250,
    difficulty: 2,
    tag: "Intermediate",
    tagColor: "bg-chart-5/10 text-chart-5 border-chart-5/20",
    description: "An unexpected ER visit leaves you with a $3,200 bill. Manage debt while keeping up with rent.",
    challenges: ["Negotiate a payment plan", "Adjust discretionary budget", "Protect your credit score"],
  },
  {
    id: "roommate_move",
    title: "Moving Out on Your Own",
    emoji: "🏠",
    xpRequired: 450,
    difficulty: 3,
    tag: "Advanced",
    tagColor: "bg-accent/10 text-accent border-accent/20",
    description: "Your roommate moved away. Can you afford the full rent alone, or do you need to downsize?",
    challenges: ["Calculate new rent ratio", "Evaluate cost vs. lifestyle", "Build a moving fund"],
  },
  {
    id: "job_loss",
    title: "Laid Off — Now What?",
    emoji: "💼",
    xpRequired: 700,
    difficulty: 3,
    tag: "Advanced",
    tagColor: "bg-accent/10 text-accent border-accent/20",
    description: "Your company downsized. Survive on unemployment benefits while your emergency fund drains.",
    challenges: ["File for unemployment", "Cut non-essential expenses", "Stretch your emergency fund"],
  },
  {
    id: "wedding",
    title: "Planning a Wedding",
    emoji: "💍",
    xpRequired: 1000,
    difficulty: 4,
    tag: "Expert",
    tagColor: "bg-chart-4/10 text-chart-4 border-chart-4/20",
    description: "Engaged! Budget a $12,000 wedding while continuing to save and avoid new debt.",
    challenges: ["Create an event budget", "Prioritize vs. cut costs", "Compare venue & vendor quotes"],
  },
  {
    id: "first_home",
    title: "Buying Your First Home",
    emoji: "🔑",
    xpRequired: 1400,
    difficulty: 4,
    tag: "Expert",
    tagColor: "bg-chart-4/10 text-chart-4 border-chart-4/20",
    description: "You're ready to stop renting. Navigate down payments, mortgages, closing costs, and PMI.",
    challenges: ["Calculate mortgage affordability", "Understand closing costs", "Compare 15 vs. 30-year loans"],
  },
  {
    id: "baby",
    title: "Starting a Family",
    emoji: "👶",
    xpRequired: 1900,
    difficulty: 5,
    tag: "Master",
    tagColor: "bg-chart-3/10 text-chart-3 border-chart-3/20",
    description: "A new baby changes everything — childcare, insurance, a bigger home. Rewrite your entire budget.",
    challenges: ["Budget for childcare costs", "Update health insurance", "Start a college savings plan"],
  },
];

// Upcoming challenges (always locked — future features)
export const UPCOMING_CHALLENGES = [
  { emoji: "📈", title: "Stock Market Simulator", desc: "Pick stocks and track a virtual portfolio for 30 days.", comingSoon: true },
  { emoji: "🏦", title: "Loan Calculator Deep Dive", desc: "Understand APR, amortization, and total interest paid.", comingSoon: true },
  { emoji: "🧾", title: "File a Full Tax Return", desc: "Walk through a 1040 form with your scenario's actual numbers.", comingSoon: true },
  { emoji: "🤝", title: "Negotiate Your Salary", desc: "Practice salary negotiation and see how it changes your lifetime earnings.", comingSoon: true },
  { emoji: "🌍", title: "Side Hustle Economics", desc: "Start a small business and manage self-employment taxes.", comingSoon: true },
];